# Copyright (c) 2015, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
classes:
  - wso2is
wso2::pack_filename: "%{::product_name}-%{::product_version}.zip"
wso2::pack_extracted_dir: "%{::product_name}-%{::product_version}"

#wso2::file_list :
#  - lib/org.wso2.ciphertool-1.0.0-wso2v2.jar

wso2::template_list :
  - repository/conf/datasources/is-datasources.xml
  - repository/conf/identity.xml
  - repository/conf/security/application-authentication.xml
#  - repository/conf/security/cipher-text.properties
#  - repository/conf/security/cipher-tool.properties
#  - bin/ciphertool.sh
#  - password-tmp

wso2::service_name: wso2is
wso2::hostname : identity.wso2test.com
wso2::mgt_hostname : identity.wso2test.com

wso2::clustering :
    enabled : true
    local_member_host : "%{::ipaddress}"
    local_member_port : 4000
    membership_scheme : wka
    domain : wso2.is.domain
    wka :
       members :
         -
           hostname : localhost
           port : 4000
         -
           hostname : localhost
           port : 4001
    multicast :
       domain : wso2.is.domain
    k8s :
    ppaas :

#wso2::registry_mounts:
#  wso2_config_db:
#    path: /_system/config
#    target_path: /_system/config
#    read_only: true
#    registry_root: /
#    enable_cache: true
#
#  wso2_gov_db:
#    path: /_system/gov
#    target_path: /_system/gov
#    read_only: true
#    registry_root: /
#    enable_cache: true

#wso2::usermgt_datasource: WSO2USER_DB

wso2::is_datasources :
  wso2is_db:
    name : WSO2IS_DB
    description: The datasource used for IS identity database
    driver_class_name : com.mysql.jdbc.Driver
    url : jdbc:mysql://mysql-server:port/dbIdentity?autoReconnect=true&amp;relaxAutoCommit=true&amp;
    username : IdentityUser
    password : 123pass
    #secretAlias :
    jndi_config : jdbc/WSO2IS_DB
    max_active: "%{hiera('wso2::datasources::common::max_active')}"
    max_wait: "%{hiera('wso2::datasources::common::max_wait')}"
    test_on_borrow: "%{hiera('wso2::datasources::common::test_on_borrow')}"
    default_auto_commit: "%{hiera('wso2::datasources::common::default_auto_commit')}"
    validation_query: "%{hiera('wso2::datasources::mysql::validation_query')}"
    validation_interval: "%{hiera('wso2::datasources::common::validation_interval')}"

wso2::master_datasources :
  wso2_config_db:
    name : WSO2_CONFIG_DB
    description: The datasource used for config registry
    driver_class_name : com.mysql.jdbc.Driver
    url : jdbc:mysql://mysql-server:port/dbIdentityConfig?autoReconnect=true&amp;relaxAutoCommit=true&amp;
    username : ConfigDbUser
    password : 123pass
    jndi_config : jdbc/WSO2_CONFIG_DB
    max_active: "%{hiera('wso2::datasources::common::max_active')}"
    max_wait: "%{hiera('wso2::datasources::common::max_wait')}"
    test_on_borrow: "%{hiera('wso2::datasources::common::test_on_borrow')}"
    validation_query: "%{hiera('wso2::datasources::mysql::validation_query')}"
    validation_interval: "%{hiera('wso2::datasources::common::validation_interval')}"

#  wso2_gov_db:
#    name : WSO2_GOV_DB
#    description: The datasource used for gov registry
#    driver_class_name : org.h2.Driver
#    url : jdbc:h2:repository/database/WSO2_GOV_DB;DB_CLOSE_ON_EXIT=FALSE;LOCK_TIMEOUT=60000
#    username : "%{hiera('wso2::datasources::common::username')}"
#    password : "%{hiera('wso2::datasources::common::password')}"
#    jndi_config : jdbc/WSO2_GOV_DB
#    max_active: "%{hiera('wso2::datasources::common::max_active')}"
#    max_wait: "%{hiera('wso2::datasources::common::max_wait')}"
#    test_on_borrow: "%{hiera('wso2::datasources::common::test_on_borrow')}"
#    validation_query: "%{hiera('wso2::datasources::mysql::validation_query')}"
#    validation_interval: "%{hiera('wso2::datasources::common::validation_interval')}"
#
#  wso2user_db :
#    name : WSO2USER_DB
#    description : The datasource is used for user mangement and userstore
#    driver_class_name : org.h2.Driver
#    url : jdbc:h2:repository/database/WSO2USER_DB?autoReconnect=true
#    username : "%{hiera('wso2::datasources::common::username')}"
#    password : "%{hiera('wso2::datasources::common::password')}"
#    jndi_config : jdbc/WSO2USER_DB
#    max_active : "%{hiera('wso2::datasources::common::max_active')}"
#    max_wait : "%{hiera('wso2::datasources::common::max_wait')}"
#    test_on_borrow : "%{hiera('wso2::datasources::common::test_on_borrow')}"
#    default_auto_commit : "%{hiera('wso2::datasources::common::default_auto_commit')}"
#    validation_query : "%{hiera('wso2::datasources::mysql::validation_query')}"
#    validation_interval : "%{hiera('wso2::datasources::common::validation_interval')}"

wso2::bps_datasources :
  bps_ds :
    name : BPS_DS
    description : The datasource used for bps
    driver_class_name : org.h2.Driver
    url : jdbc:h2:file:repository/database/jpadb;DB_CLOSE_ON_EXIT=FALSE;MVCC=TRUE
    username : wso2carbon
    password : wso2carbon
    jndi_config : bpsds
    max_active : "%{hiera('wso2::datasources::common::max_active')}"
    max_wait : "%{hiera('wso2::datasources::common::max_wait')}"
    test_on_borrow : "%{hiera('wso2::datasources::common::test_on_borrow')}"
    default_auto_commit : "%{hiera('wso2::datasources::common::default_auto_commit')}"
    validation_query : "%{hiera('wso2::datasources::mysql::validation_query')}"
    validation_interval : "%{hiera('wso2::datasources::common::validation_interval')}"

wso2::metrics_datasources :
  metrics_ds :
    name : WSO2_METRICS_DB
    description : The default datasource used for WSO2 Carbon Metrics
    driver_class_name : org.h2.Driver
    url : jdbc:h2:repository/database/WSO2METRICS_DB;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
    username : wso2carbon
    password : wso2carbon
    jndi_config : WSO2MetricsDB
    max_active : "%{hiera('wso2::datasources::common::max_active')}"
    max_wait : "%{hiera('wso2::datasources::common::max_wait')}"
    test_on_borrow : "%{hiera('wso2::datasources::common::test_on_borrow')}"
    default_auto_commit : "%{hiera('wso2::datasources::common::default_auto_commit')}"
    validation_query : "%{hiera('wso2::datasources::mysql::validation_query')}"
    validation_interval : "%{hiera('wso2::datasources::common::validation_interval')}"

# Secure vault configuration
wso2::enable_secure_vault : false
wso2::secure_vault_configs :
  key_store_password :
    secret_alias: Carbon.Security.KeyStore.Password
    secret_alias_value: carbon.xml//Server/Security/KeyStore/Password,true
    password: wso2carbon
  key_store_key_password :
    secret_alias: Carbon.Security.KeyStore.KeyPassword
    secret_alias_value: carbon.xml//Server/Security/KeyStore/KeyPassword,true
    password: wso2carbon
  trust_store_password :
    secret_alias: Carbon.Security.TrustStore.Password
    secret_alias_value: carbon.xml//Server/Security/TrustStore/Password,true
    password: wso2carbon
  user_manager_admin_password :
    secret_alias: UserManager.AdminUser.Password
    secret_alias_value: user-mgt.xml//UserManager/Realm/Configuration/AdminUser/Password,true
    password: admin
  wso2_carbon_db_password :
    secret_alias: Datasources.WSO2_CARBON_DB.Configuration.Password
    secret_alias_value: master-datasources.xml//datasources-configuration/datasources/datasource[name='WSO2_CARBON_DB']/definition[@type='RDBMS']/configuration/password,false
    password: wso2carbon
#  wso2am_db_password :
#    secret_alias: Datasource.WSO2AM_DB.configuration.password
#    secret_alias_value: am-datasources.xml//datasources-configuration/datasources/datasource[name='WSO2AM_DB']/definition[@type='RDBMS']/configuration/password,false
#    password: wso2carbon
#  wso2am_stats_db_password :
#    secret_alias: Datasource.WSO2AM_STATS_DB.configuration.password
#    secret_alias_value: master-datasources.xml//datasources-configuration/datasources/datasource[name='WSO2AM_STATS_DB']/definition[@type='RDBMS']/configuration/password,false
#    password: wso2carbon
#  wso2_config_db_password :
#    secret_alias: Datasources.WSO2_CONFIG_DB.Configuration.Password
#    secret_alias_value: master-datasources.xml//datasources-configuration/datasources/datasource[name='WSO2_CONFIG_DB']/definition[@type='RDBMS']/configuration/password,false
#    password: wso2carbon
#  wso2_gov_db_password :
#    secret_alias: Datasources.WSO2_GOV_DB.Configuration.Password
#    secret_alias_value: master-datasources.xml//datasources-configuration/datasources/datasource[name='WSO2_GOV_DB']/definition[@type='RDBMS']/configuration/password,false
#    password: wso2carbon
#  connector_key_store_password :
#    secret_alias: Server.Service.Connector.keystorePass
#    secret_alias_value: catalina-server.xml//Server/Service/Connector[@keystorePass],false
#    password: wso2carbon
#  user_store_manager_connection_password:
#    secret_alias: UserStoreManager.Property.ConnectionPassword
#    secret_alias_value: user-mgt.xml//UserManager/Realm/UserStoreManager/Property[@name='ConnectionPassword'],true
#    password: admin
#  user_store_manager_password:
#    secret_alias: UserStoreManager.Property.password
#    secret_alias_value: user-mgt.xml//UserManager/Realm/UserStoreManager/Property[@name='password'],true
#    password: admin
#  auth_manager_password:
#    secret_alias: AuthManager.Password
#    secret_alias_value: api-manager.xml//APIManager/AuthManager/Password,true
#    password: admin
#  api_gateway_password:
#    secret_alias: APIGateway.Password
#    secret_alias_value: api-manager.xml//APIManager/APIGateway/Environments/Environment/Password,true
#    password: admin
#  api_key_manager_password:
#    secret_alias: APIKeyManager.Password
#    secret_alias_value: api-manager.xml//APIManager/APIKeyManager/Password,true
#    password: admin
#  api_store_password:
#    secret_alias: APIStore.Password
#    secret_alias_value: api-manager.xml//APIManager/APIStore/Password,true
#    password: admin
#  api_usage_tracking_bam_password:
#    secret_alias: APIUsageTracking.BAMPassword
#    secret_alias_value: api-manager.xml//APIManager/APIUsageTracking/BAMPassword,true
#    password: admin
#  api_usage_tracking_jdbc_password:
#    secret_alias:  APIUsageTracking.JDBCPassword
#    secret_alias_value:api-manager.xml//APIManager/APIUsageTracking/JDBCPassword,true
#    password: admin
#  database_password:
#    secret_alias: Database.Password
#    secret_alias_value: api-manager.xml//APIManager/Database/Password,true
#    password: wso2carbon
#  user_trusted_RPStore_password:
#    secret_alias: Security.UserTrustedRPStore.Password
#    secret_alias_value: identity.xml//Server/Security/UserTrustedRPStore/Password
#    password: wso2carbon
#  user_trusted_RPStore_key_password:
#    secret_alias: Security.UserTrustedRPStore.KeyPassword
#    secret_alias_value: identity.xml//Server/Security/UserTrustedRPStore/KeyPassword
#    password: wso2carbon
#  identity_system_store_pass:
#    secret_alias: Identity.System.StorePass
#    secret_alias_value: identity.xml//Server/Identity/System/StorePass
#    password: wso2carbon
#  xmpp_password:
#    secret_alias: MultifactorAuthentication.XMPPSettings.XMPPConfig.XMPPPassword
#    secret_alias_value: identity.xml//MultifactorAuthentication/XMPPSettings/XMPPConfig/XMPPPassword
#    password: wso2carbon
#  bpelepr_password:
#    secret_alias:  BPELEPR.Password
#    secret_alias_value:securedinvoke.epr//EndpointReference/Metadata/transport/authorization-password,false
#    password: admin
#  axis2_https_listener_trust_store_password:
#    secret_alias: Axis2.Https.Listener.TrustStore.Password
#    secret_alias_value: axis2.xml//axisconfig/transportReceiver[@name='https']/parameter[@name='truststore']/TrustStore/Password,false
#    password: wso2carbon
#  axis2_https_listener_key_store_password:
#    secret_alias: Axis2.Https.Listener.KeyStore.Password
#    secret_alias_value: axis2.xml//axisconfig/transportReceiver[@name='https']/parameter[@name='keystore']/KeyStore/Password,false
#    password: wso2carbon
#  axis2_https_listener_key_store_key_password:
#    secret_alias: Axis2.Https.Listener.KeyStore.KeyPassword
#    secret_alias_value: axis2.xml//axisconfig/transportReceiver[@name='https']/parameter[@name='keystore']/KeyStore/KeyPassword,false
#    password: wso2carbon
#  axis2_https_sender_trust_store_password:
#    secret_alias: Axis2.Https.Listener.TrustStore.Password
#    secret_alias_value: axis2.xml//axisconfig/transportSender[@name='https']/parameter[@name='truststore']/TrustStore/Password,false
#    password: wso2carbon
#  axis2_https_sender_key_store_password:
#    secret_alias: Axis2.Https.Listener.KeyStore.Password
#    secret_alias_value: axis2.xml//axisconfig/transportSender[@name='https']/parameter[@name='keystore']/KeyStore/Password,false
#    password: wso2carbon
#  axis2_https_sender_key_store_key_password:
#    secret_alias: Axis2.Https.Listener.KeyStore.KeyPassword
#    secret_alias_value: axis2.xml//axisconfig/transportSender[@name='https']/parameter[@name='keystore']/KeyStore/KeyPassword,false
#    password: wso2carbon
#  axis2_mailto_parameter_password:
#    secret_alias: Axis2.Mailto.Parameter.Password
#    secret_alias_value: axis2.xml//axisconfig/transportSender[@name='mailto']/parameter[@name='mail.smtp.password'],false
#    password: wso2carbon
#  remote_message_broker_password:
#    secret_alias: eventBrokerConfig.eventBroker.deliveryManager.remoteMessageBroker.password
#    secret_alias_value: event-broker.xml//eventBrokerConfig/eventBroker/deliveryManager/remoteMessageBroker/password,false
#    password: admin


# for K8s scenario, need to enable proxy port to match NodePorts
# defined for servlet HTTP and HTTPS transport in K8s Service definition
wso2::ports:
  proxyPort :
    http: 80
    https: 443
